export interface BusinessCategoryDefinition {
  category: string
  subcategories: string[]
}

export const BUSINESS_CATEGORIES: BusinessCategoryDefinition[] = [
  {
    category: 'Retail & Shopping',
    subcategories: [
      'General Store',
      'Grocery / Kirana Store',
      'Supermarket',
      'Department Store',
      'Clothing Store',
      "Men's Clothing",
      "Women's Clothing",
      'Kids Clothing',
      'Fashion Boutique',
      'Footwear Store',
      'Jewelry Store',
      'Cosmetics Store',
      'Electronics Store',
      'Mobile Store',
      'Furniture Store',
      'Home Decor Store',
      'Hardware Store',
      'Book Store',
      'Stationery Store',
      'Gift Shop',
      'Flower Shop',
      'Toy Store',
      'Baby Products Store',
      'Sports Goods Store',
      'Optical Store',
      'Watch Store',
      'Bags & Luggage Store',
      'Kitchenware Store',
      'Saree Store',
      'Uniform Store',
      'Other Retail Store',
    ],
  },
  {
    category: 'Food & Beverage',
    subcategories: [
      'Restaurant',
      'Fine Dining Restaurant',
      'Family Restaurant',
      'Fast Food Restaurant',
      'Cafe',
      'Coffee Shop',
      'Tea Shop',
      'Bakery',
      'Cake Shop',
      'Sweet Shop / Mithai Shop',
      'Ice Cream Parlor',
      'Juice Center',
      'Cloud Kitchen',
      'Tiffin Service',
      'Catering Service',
      'Food Truck',
      'Street Food Stall',
      'Pizza Restaurant',
      'Burger Shop',
      'Biryani Restaurant',
      'South Indian Restaurant',
      'North Indian Restaurant',
      'Chinese Restaurant',
      'Continental Restaurant',
      'Vegetarian Restaurant',
      'Non-Vegetarian Restaurant',
      'Bar & Lounge',
      'Dhaba',
      'Breakfast Center',
      'Other Food Business',
    ],
  },
  {
    category: 'Healthcare & Medical',
    subcategories: [
      'Hospital',
      'Clinic',
      'Multi-Specialty Clinic',
      'General Physician',
      'Dentist',
      'Dermatologist',
      'Pediatrician',
      'Gynecologist',
      'Orthopedic Doctor',
      'ENT Specialist',
      'Eye Clinic / Ophthalmologist',
      'Physiotherapist',
      'Psychologist',
      'Psychiatrist',
      'Ayurveda Clinic',
      'Homeopathy Clinic',
      'Unani Clinic',
      'Naturopathy Center',
      'Pharmacy / Medical Store',
      'Diagnostic Center',
      'Pathology Lab',
      'Radiology Center',
      'Blood Bank',
      'Ambulance Service',
      'Home Healthcare',
      'Nursing Service',
      'Medical Equipment Supplier',
      'Medical Equipment Rental',
      'Rehabilitation Center',
      'Other Medical Service',
    ],
  },
  {
    category: 'Beauty & Personal Care',
    subcategories: [
      'Beauty Salon',
      'Hair Salon',
      'Barbershop',
      "Men's Grooming Salon",
      'Beauty Parlor',
      'Spa',
      'Massage Center',
      'Makeup Artist',
      'Bridal Makeup Artist',
      'Nail Studio',
      'Skincare Center',
      'Hair Removal Service',
      'Eyebrow Service',
      'Eyelash Service',
      'Mehendi Artist',
      'Tattoo Studio',
      'Piercing Studio',
      'Hair Extension Service',
      'Hair Treatment Center',
      'Cosmetics & Beauty Supply',
      'Other Beauty Service',
    ],
  },
  {
    category: 'Fitness & Sports',
    subcategories: [
      'Gym',
      'Fitness Center',
      'Yoga Studio',
      'Pilates Studio',
      'Personal Trainer',
      'Zumba Class',
      'Dance Fitness Class',
      'Martial Arts Academy',
      'Boxing Academy',
      'Sports Academy',
      'Cricket Academy',
      'Football Academy',
      'Badminton Academy',
      'Tennis Academy',
      'Swimming Classes',
      'Sports Club',
      'Nutrition Coach',
      'Wellness Coach',
      'Athletic Training Center',
      'Indoor Sports Center',
      'Outdoor Sports Facility',
      'Other Fitness / Sports Service',
    ],
  },
  {
    category: 'Education & Training',
    subcategories: [
      'School',
      'Preschool',
      'College',
      'Coaching Center',
      'Tuition Center',
      'Private Tutor',
      'Online Tutor',
      'Competitive Exam Coaching',
      'NEET Coaching',
      'JEE Coaching',
      'UPSC Coaching',
      'Government Exam Coaching',
      'Computer Institute',
      'Coding Classes',
      'Language Classes',
      'English Speaking Classes',
      'Music Classes',
      'Dance Classes',
      'Art Classes',
      'Skill Training Institute',
      'Vocational Training Center',
      'Corporate Training',
      'Online Course Provider',
      'Test Preparation Center',
      'Other Education Service',
    ],
  },
  {
    category: 'Technology & IT Services',
    subcategories: [
      'Software Development Company',
      'Web Development Company',
      'Mobile App Development',
      'IT Consulting',
      'IT Support',
      'Computer Networking',
      'Cloud Services',
      'Cybersecurity Services',
      'Data Analytics',
      'AI / Machine Learning Services',
      'SaaS Company',
      'ERP Software Provider',
      'CRM Software Provider',
      'POS Software Provider',
      'Inventory Software Provider',
      'Domain & Hosting Provider',
      'Website Maintenance',
      'Automation Services',
      'Database Services',
      'UI/UX Technology Service',
      'Other IT Service',
    ],
  },
  {
    category: 'Professional Services',
    subcategories: [
      'Chartered Accountant',
      'Tax Consultant',
      'Auditor',
      'Company Secretary',
      'Business Consultant',
      'Management Consultant',
      'Startup Consultant',
      'Financial Consultant',
      'Compliance Consultant',
      'Project Consultant',
      'Engineering Consultant',
      'Surveyor',
      'Valuation Consultant',
      'Insurance Consultant',
      'Documentation Consultant',
      'Career Consultant',
      'Immigration Consultant',
      'Visa Consultant',
      'Other Professional Service',
    ],
  },
  {
    category: 'Home Services',
    subcategories: [
      'Electrician',
      'Plumber',
      'Carpenter',
      'Painter',
      'Mason',
      'Handyman',
      'Home Cleaning',
      'Deep Cleaning',
      'Housekeeping',
      'Pest Control',
      'Laundry Service',
      'Dry Cleaning',
      'AC Service',
      'RO Service',
      'Appliance Installation',
      'Gardener',
      'Water Tank Cleaning',
      'Sofa Cleaning',
      'Carpet Cleaning',
      'Bathroom Cleaning',
      'Septic Tank Cleaning',
      'Home Renovation Service',
      'Other Home Service',
    ],
  },
  {
    category: 'Automotive',
    subcategories: [
      'Car Repair',
      'Bike Repair',
      'Auto Garage',
      'Car Wash',
      'Bike Wash',
      'Car Detailing',
      'Tyre Shop',
      'Battery Shop',
      'Auto Parts Store',
      'Car Accessories',
      'Bike Accessories',
      'Vehicle Towing',
      'Roadside Assistance',
      'Driving School',
      'Car Dealer',
      'Bike Dealer',
      'Used Car Dealer',
      'EV Charging Station',
      'PUC Center',
      'Auto Insurance Agent',
      'Vehicle Finance Consultant',
      'Other Automotive Service',
    ],
  },
  {
    category: 'Real Estate',
    subcategories: [
      'Real Estate Agent',
      'Property Dealer',
      'Property Broker',
      'Builder',
      'Real Estate Developer',
      'Residential Property Dealer',
      'Commercial Property Dealer',
      'Land Dealer',
      'Rental Property Agent',
      'Property Management',
      'PG Accommodation',
      'Hostel Accommodation',
      'Warehouse Rental',
      'Farmhouse Rental',
      'Real Estate Consultant',
      'Property Valuer',
      'Property Documentation Service',
      'Other Real Estate Service',
    ],
  },
  {
    category: 'Construction & Interior',
    subcategories: [
      'Construction Contractor',
      'Civil Contractor',
      'Builder',
      'Architect',
      'Interior Designer',
      'Home Renovation Contractor',
      'Modular Kitchen Provider',
      'Flooring Contractor',
      'Tile & Marble Contractor',
      'Glass & Aluminum Work',
      'False Ceiling Contractor',
      'Waterproofing Contractor',
      'Electrical Contractor',
      'Plumbing Contractor',
      'Painting Contractor',
      'Fabrication Work',
      'Welding Work',
      'Construction Material Supplier',
      'Landscaping Service',
      'Other Construction Service',
    ],
  },
  {
    category: 'Finance & Insurance',
    subcategories: [
      'Bank',
      'NBFC',
      'Loan Consultant',
      'Home Loan Consultant',
      'Business Loan Consultant',
      'Personal Loan Consultant',
      'Gold Loan Provider',
      'Insurance Agent',
      'Insurance Broker',
      'Life Insurance',
      'Health Insurance',
      'Vehicle Insurance',
      'Investment Advisor',
      'Mutual Fund Distributor',
      'Stock Broker',
      'Financial Planner',
      'Microfinance Service',
      'Credit Cooperative',
      'Payment Service Provider',
      'Fintech Service',
      'Other Finance Service',
    ],
  },
  {
    category: 'Travel & Hospitality',
    subcategories: [
      'Hotel',
      'Resort',
      'Guest House',
      'Homestay',
      'Hostel',
      'PG Accommodation',
      'Travel Agency',
      'Tour Operator',
      'Taxi Service',
      'Cab Service',
      'Car Rental',
      'Bus Ticketing',
      'Flight Booking',
      'Train Ticketing',
      'Visa Assistance',
      'Immigration Travel Service',
      'Travel Guide',
      'Adventure Tourism',
      'Pilgrimage Tour Provider',
      'Vacation Rental',
      'Other Travel Service',
    ],
  },
  {
    category: 'Event Services',
    subcategories: [
      'Event Planner',
      'Wedding Planner',
      'Birthday Planner',
      'Corporate Event Planner',
      'Banquet Hall',
      'Marriage Garden',
      'Catering Service',
      'Decoration Service',
      'Tent House',
      'DJ Service',
      'Sound & Light Service',
      'Event Equipment Rental',
      'Anchor / Event Host',
      'Stage Setup',
      'Party Supplies',
      'Florist for Events',
      'Invitation Card Service',
      'Exhibition Stall Setup',
      'Other Event Service',
    ],
  },
  {
    category: 'Photography & Creative Services',
    subcategories: [
      'Photographer',
      'Wedding Photographer',
      'Product Photographer',
      'Event Photographer',
      'Portrait Photographer',
      'Photo Studio',
      'Videographer',
      'Cinematographer',
      'Drone Photography',
      'Photo Editing',
      'Video Editing',
      'Graphic Designer',
      'Logo Designer',
      'Illustrator',
      'Animator',
      'Motion Graphics Designer',
      '3D Artist',
      'Voiceover Artist',
      'Content Creator',
      'Creative Studio',
      'Other Creative Service',
    ],
  },
  {
    category: 'Marketing & Advertising',
    subcategories: [
      'Digital Marketing Agency',
      'SEO Agency',
      'Social Media Marketing',
      'Google Ads Expert',
      'Meta Ads Expert',
      'Content Marketing',
      'Branding Agency',
      'Advertising Agency',
      'Influencer Marketing',
      'Affiliate Marketing',
      'Performance Marketing',
      'PR Agency',
      'Event Marketing',
      'Outdoor Advertising',
      'Print Media',
      'Email Marketing',
      'SMS Marketing',
      'WhatsApp Marketing',
      'Lead Generation Agency',
      'Market Research Agency',
      'Other Marketing Service',
    ],
  },
  {
    category: 'Media & Entertainment',
    subcategories: [
      'Film Production',
      'Video Production',
      'Music Studio',
      'Recording Studio',
      'News Media Company',
      'Digital Media Company',
      'YouTube Studio',
      'Podcast Studio',
      'Theater Group',
      'Dance Group',
      'Music Band',
      'Artist Management',
      'Event Entertainment',
      'Game Zone',
      'Amusement Center',
      'Cinema',
      'Karaoke Lounge',
      'Radio / Podcast Production',
      'Other Entertainment Service',
    ],
  },
  {
    category: 'Manufacturing & Industrial',
    subcategories: [
      'Textile Manufacturing',
      'Garment Manufacturing',
      'Food Processing',
      'Plastic Products Manufacturing',
      'Metal Fabrication',
      'Machinery Manufacturing',
      'Furniture Manufacturing',
      'Chemical Manufacturing',
      'Packaging Manufacturing',
      'Electronics Manufacturing',
      'Electrical Equipment Manufacturing',
      'Auto Components Manufacturing',
      'Paper Products Manufacturing',
      'Handicraft Manufacturing',
      'Leather Products Manufacturing',
      'Rubber Products Manufacturing',
      'Pharmaceutical Manufacturing',
      'Industrial Supplies Manufacturing',
      'Other Manufacturing Business',
    ],
  },
  {
    category: 'Wholesale & Distribution',
    subcategories: [
      'FMCG Distributor',
      'Grocery Wholesale',
      'Food Grain Wholesale',
      'Fruits & Vegetables Wholesale',
      'Garments Wholesale',
      'Footwear Wholesale',
      'Electronics Wholesale',
      'Mobile Accessories Wholesale',
      'Building Material Wholesale',
      'Medicine Distributor',
      'Stationery Wholesale',
      'Furniture Wholesale',
      'Hardware Wholesale',
      'Chemical Supplier',
      'Packaging Supplier',
      'Beverage Distributor',
      'B2B Supplier',
      'Other Wholesale Business',
    ],
  },
  {
    category: 'Agriculture & Farming',
    subcategories: [
      'Farm',
      'Organic Farm',
      'Dairy Farm',
      'Poultry Farm',
      'Fish Farm / Aquaculture',
      'Nursery',
      'Seeds Supplier',
      'Fertilizer Supplier',
      'Agricultural Equipment Supplier',
      'Irrigation Service',
      'Farm Produce Supplier',
      'Floriculture',
      'Beekeeping',
      'Animal Feed Supplier',
      'Agro Chemicals Supplier',
      'Cold Storage',
      'Grain Trader',
      'Agricultural Consultant',
      'Horticulture',
      'Mushroom Farming',
      'Other Agriculture Business',
    ],
  },
  {
    category: 'Pets & Animal Care',
    subcategories: [
      'Pet Shop',
      'Veterinary Clinic',
      'Animal Hospital',
      'Pet Grooming',
      'Pet Boarding',
      'Pet Daycare',
      'Pet Training',
      'Pet Food Store',
      'Pet Accessories Store',
      'Aquarium Store',
      'Animal Shelter',
      'Pet Adoption Center',
      'Pet Ambulance',
      'Livestock Veterinary Service',
      'Other Pet Service',
    ],
  },
  {
    category: 'Religious Organizations',
    subcategories: [
      'Temple',
      'Mosque',
      'Church',
      'Gurudwara',
      'Jain Temple',
      'Buddhist Center',
      'Ashram',
      'Religious Trust',
      'Spiritual Center',
      'Meditation Center',
      'Priest / Pandit Service',
      'Puja Service',
      'Religious Event Service',
      'Pilgrimage Organizer',
      'Astrology Service',
      'Vastu Consultant',
      'Other Religious Service',
    ],
  },
  {
    category: 'NGOs & Non-Profit',
    subcategories: [
      'NGO',
      'Charitable Trust',
      'Foundation',
      'Social Welfare Organization',
      'Education NGO',
      'Healthcare NGO',
      'Animal Welfare NGO',
      'Environmental NGO',
      'Women Empowerment Organization',
      'Child Welfare Organization',
      'Old Age Support Organization',
      'Disability Support Organization',
      'Disaster Relief Organization',
      'Community Organization',
      'Blood Donation Group',
      'Food Distribution Organization',
      'Other Non-Profit Organization',
    ],
  },
  {
    category: 'Government & Public Services',
    subcategories: [
      'Municipal Office',
      'Panchayat Office',
      'Government Department',
      'Public Library',
      'Post Office',
      'Police Station',
      'Fire Station',
      'Public Hospital',
      'Public School',
      'Public Utility Office',
      'Public Service Center',
      'Aadhaar Center',
      'Common Service Center',
      'Passport Service Center',
      'RTO / Transport Office',
      'Community Hall',
      'Other Public Service',
    ],
  },
  {
    category: 'Legal Services',
    subcategories: [
      'Advocate / Lawyer',
      'Law Firm',
      'Legal Consultant',
      'Notary',
      'Civil Lawyer',
      'Criminal Lawyer',
      'Family Lawyer',
      'Property Lawyer',
      'Corporate Lawyer',
      'Tax Lawyer',
      'Labour Lawyer',
      'Consumer Court Lawyer',
      'Immigration Lawyer',
      'Intellectual Property Lawyer',
      'Arbitration Service',
      'Mediation Service',
      'Legal Documentation Service',
      'Other Legal Service',
    ],
  },
  {
    category: 'Logistics & Transportation',
    subcategories: [
      'Courier Service',
      'Parcel Delivery',
      'Packers & Movers',
      'Moving Service',
      'Storage Service',
      'Transport Company',
      'Freight Forwarder',
      'Trucking Service',
      'Local Delivery Service',
      'Warehousing',
      'Cold Chain Logistics',
      'Cargo Service',
      'Shipping Agent',
      'Railway Cargo Service',
      'E-Commerce Delivery Partner',
      'Fleet Operator',
      'Tempo / Truck Rental',
      'International Logistics',
      'Other Logistics Service',
    ],
  },
  {
    category: 'Security Services',
    subcategories: [
      'Security Guard Agency',
      'CCTV Installation',
      'CCTV Dealer',
      'Alarm System Provider',
      'Fire Safety Equipment',
      'Fire Extinguisher Service',
      'Access Control System',
      'Biometric Attendance System',
      'Bouncer Service',
      'Event Security',
      'Private Detective',
      'Safety Training',
      'Security Equipment Dealer',
      'Locksmith',
      'Other Security Service',
    ],
  },
  {
    category: 'Repair & Maintenance',
    subcategories: [
      'Mobile Repair',
      'Laptop Repair',
      'Computer Repair',
      'Appliance Repair',
      'AC Repair',
      'Refrigerator Repair',
      'Washing Machine Repair',
      'TV Repair',
      'Electrical Repair',
      'Plumbing Repair',
      'Furniture Repair',
      'Watch Repair',
      'Shoe Repair',
      'Camera Repair',
      'Generator Repair',
      'Sewing Machine Repair',
      'Elevator Maintenance',
      'Industrial Machine Maintenance',
      'Other Repair Service',
    ],
  },
  {
    category: 'Rental Services',
    subcategories: [
      'Car Rental',
      'Bike Rental',
      'Equipment Rental',
      'Construction Equipment Rental',
      'Party Equipment Rental',
      'Furniture Rental',
      'Costume Rental',
      'Camera Rental',
      'Sound & Light Rental',
      'Generator Rental',
      'Appliance Rental',
      'Office Space Rental',
      'Coworking Space Rental',
      'Warehouse Rental',
      'Medical Equipment Rental',
      'Sports Equipment Rental',
      'Book Rental',
      'Dress Rental',
      'Jewelry Rental',
      'Other Rental Service',
    ],
  },
  {
    category: 'E-Commerce & Online Businesses',
    subcategories: [
      'Online Store',
      'D2C Brand',
      'Marketplace Seller',
      'Dropshipping Store',
      'Online Grocery',
      'Online Fashion Store',
      'Online Electronics Store',
      'Online Pharmacy',
      'Online Food Delivery',
      'Online Course Platform',
      'Digital Products Seller',
      'Subscription Box Business',
      'Print-on-Demand Store',
      'Affiliate Business',
      'Social Commerce Store',
      'Instagram Store',
      'WhatsApp Store',
      'Other Online Business',
    ],
  },
  {
    category: 'Business Support Services',
    subcategories: [
      'Coworking Space',
      'Virtual Office',
      'Office Supplies',
      'BPO / Call Center',
      'Data Entry Service',
      'Back Office Service',
      'Recruitment Agency',
      'HR Consultant',
      'Payroll Service',
      'Staffing Agency',
      'Facility Management',
      'Business Registration Service',
      'Documentation Service',
      'Translation Service',
      'Admin Support',
      'Procurement Service',
      'Corporate Gifting',
      'Other Business Support',
    ],
  },
  {
    category: 'Telecommunications',
    subcategories: [
      'Mobile Network Store',
      'Broadband Provider',
      'Internet Service Provider',
      'Fiber Internet Provider',
      'SIM Card Dealer',
      'DTH Service',
      'Cable TV Provider',
      'Telecom Equipment Supplier',
      'Tower Service Provider',
      'VoIP Service',
      'EPABX Service',
      'Networking & Cabling',
      'Satellite Communication Service',
      'Telecom Consultant',
      'Other Telecom Service',
    ],
  },
  {
    category: 'Energy & Environment',
    subcategories: [
      'Solar Installer',
      'Solar Products Dealer',
      'EV Charging Station',
      'Battery & Inverter Dealer',
      'Generator Supplier',
      'Renewable Energy Consultant',
      'Waste Management',
      'Recycling Service',
      'Scrap Dealer',
      'Other Energy Service',
    ],
  },
  {
    category: 'Childcare & Senior Care',
    subcategories: [
      'Daycare',
      'Preschool / Play School',
      'Babysitting Service',
      'Nanny Service',
      'Child Activity Center',
      'After-School Care',
      'Special Needs Care',
      'Senior Care Service',
      'Elderly Home Care',
      'Nursing Attendant',
      'Old Age Home',
      'Senior Physiotherapy',
      'Dementia Care',
      'Assisted Living',
      'Home Health Aide',
      'Other Care Service',
    ],
  },
  {
    category: 'Import & Export',
    subcategories: [
      'Exporter',
      'Importer',
      'Export Consultant',
      'Import Consultant',
      'Customs Clearance Agent',
      'CHA Service',
      'International Freight Service',
      'Product Sourcing Service',
      'Export Documentation',
      'Import Documentation',
      'Foreign Trade Consultant',
      'Spice Exporter',
      'Textile Exporter',
      'Handicraft Exporter',
      'Agricultural Exporter',
      'Machinery Importer',
      'B2B Export Supplier',
      'Other Import / Export Business',
    ],
  },
  {
    category: 'Freelancers',
    subcategories: [
      'Graphic Designer',
      'Web Developer',
      'App Developer',
      'Video Editor',
      'Content Writer',
      'Copywriter',
      'Social Media Manager',
      'SEO Freelancer',
      'Digital Marketing Freelancer',
      'Virtual Assistant',
      'Data Entry Freelancer',
      'Translator',
      'Voice Artist',
      'Photographer',
      'Consultant',
      'Online Tutor',
      'Accountant',
      'HR Freelancer',
      'UI/UX Designer',
      '3D Artist',
      'Animator',
      'Other Freelancer',
    ],
  },
  {
    category: 'Other',
    subcategories: [
      'Other Local Business',
      'Other Online Business',
      'Other Product Seller',
      'Other Service Provider',
      'Other Consultant',
      'Other Institution',
      'Other Organization',
      'Other Manufacturer',
      'Other Distributor',
      'Not Listed',
    ],
  },
]

export const BUSINESS_CATEGORY_OPTIONS = BUSINESS_CATEGORIES.map((entry) => entry.category)

export function getSubcategoriesForCategory(category: string): string[] {
  const match = BUSINESS_CATEGORIES.find((entry) => entry.category === category)
  return match ? match.subcategories : []
}
